# abbr.toml と rcparams.toml にある以外の設定情報をここにまとめましょう。
# 以下は例ですので、自由に書き換えてください。
[task]
  interval_sec = 1.3

  [task.outlier]
    max_std = 2.5
    min_n_response = 10

[eeg]
  correct_baseline = true
  names_band = ['theta', 'alpha', 'beta']
  bands = [
    [8.0, 12.0],
    [4.0, 8.0],
    [12.0, 30.0],
  ]